### ISSUE TITLE
Create Navbar

### ISSUE THREAD

**Issue by alamiiin** [Alamin02/pluto#1]
Create a basic navigation bar from the PSD file.

**Comment by farhan2077** [comment]
PSD navbar design

![2021-01-19-11-14-06](https://user-images.githubusercontent.com/32035481/104990803-93931580-5a47-11eb-8cd1-405d371e0ce4.png)

**Comment by farhan2077** [comment]
Final Navbar design:

![2021-01-20-01-26-03](https://user-images.githubusercontent.com/32035481/105083285-e956d480-5abe-11eb-813f-2b93c7154db7.png)
